### ISSUE TITLE
Operator subscriptions failing to install

### ISSUE THREAD

**Issue by seandst** [piqe-test-libraries/piqe-ocp-lib#44]
On a recent attempt to install operators to an OCP 4.7 cluster from the operator hub, the installation process for installation never completed. This happened with every operator I subscribed, but manually installing/subscribing the operator via the UI worked. I think the issue is related to a field that may be missing from the Subscription spec.

This is an example (simplified) of a manually-created Subscription object:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: '4.7'
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: local-storage-operator.4.7.0-202105210300.p0
```

And here's the corresponding bits from `create_subscription`: https://github.com/piqe-test-libraries/piqe-ocp-lib/blob/aa2d75d93e0a585f70b5c0563e7051039d2b22ef/piqe_ocp_lib/api/resources/ocp_operators.py#L421-L432

That `startingCSV` field is missing in the library-generated snippet, and is also referenced in the `status` section of the Subscription of a working operator install, leading me to believe it may be a required field for installing some or all operators. Without this field, the "InstallPlan" that is created/related with this Subscription enters a perpetual "updating" state. The system event logs shows that operator images are successfully pulled into the cluster, but the operator never becomes active.

I assume the value for the `startingCSV` field is somewhere in the operator metadata, but haven't dug far enough into it to find out.
